services:
  syncthing:
    container_name: syncthing
    image: syncthing/syncthing:latest
    ports:
      - 8384:8384
      - 21027:21027/udp
      - 22000:22000/tcp
      - 22000:22000/udp
    restart: unless-stopped
    volumes:
      - /volume1/syncthing/data:/var/syncthing
